[build]
  command = "npm install"
  publish = "dist"
  functions = "netlify/functions"

# Маршруты для страниц
[[redirects]]
  from = "/about"
  to = "/about/index.html"
  status = 200

[[redirects]]
  from = "/portfolio"
  to = "/portfolio/index.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact/index.html"
  status = 200

[[redirects]]
  from = "/chat"
  to = "/chat/index.html"
  status = 200

# Маршрут для API функций
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Маршрут для статических файлов
[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

# Маршрут для корневой страницы
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 5000
  port = 8888
  publish = "dist"

# CORS и кэширование
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Cache-Control = "public, max-age=0, must-revalidate"